name: Docker Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build + Push
        run: |
          echo "Logging into registry..."
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker-compose build
          docker-compose push
