name: Docker Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docker-compose-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build all services
        run: docker compose build

  python-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run engine test
        run: python -m pytest tests/test_engine.py

